export const USER_LOGIN_REQUEST = 'USER-LOGIN-REQUEST';
export const USER_LOGIN_SUCCESS = 'USER-LOGIN-SUCCESS';
export const USER_LOGIN_FAIL = 'USER-LOGIN-FAIL';
export const USER_LOGOUT = 'USER-LOGOUT';

export const USER_REGISTER_REQUEST = 'USER-REGISTER-REQUEST';
export const USER_REGISTER_SUCCESS = 'USER-REGISTER-SUCCESS';
export const USER_REGISTER_FAIL = 'USER-REGISTER-FAIL';
